#Version: 0.0.1
FROM ubuntu
MAINTAINER AuThor LMY "lmysoar@hotmail.com"
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y python
RUN apt-get update
RUN apt-get install -y openjdk-7-jdk
RUN apt-get install -y openjdk-7-jre