// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = [
    {
      host: 'http://192.168.3.103:3000',
      name: "judge1",
      id: 1,
      tmpfs_size: 200,
      cpu: [0],
      secret_key: "沛神太帅了"
    }, {
      host: 'http://127.0.0.1:3000',
      name: "judge2",
      id: 2,
      tmpfs_size: 200,
      cpu: [1],
      secret_key: "梁明阳专用judge"
    }
  ];

}).call(this);

//# sourceMappingURL=config.js.map
