// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = [
    {
      host: 'http://127.0.0.1:4000',
      name: "judge3",
      website: "lmy",
      id: 1,
      memory_limit: 200,
      cpu_set: [2],
      secret_key: "沛神太帅了"
    }, {
      host: 'http://127.0.0.1:4000',
      name: "judge4",
      website: "lmy",
      id: 2,
      memory_limit: 200,
      cpu_set: [3],
      secret_key: "梁明阳专用judge"
    }
  ];

}).call(this);

//# sourceMappingURL=config.js.map
