// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = [
    {
      host: 'http://127.0.0.1:3000',
      name: "judge1",
      id: 1,
      memory_limit: 200,
      cpuset: [0, 1],
      secret_key: "沛神太帅了"
    }
  ];

}).call(this);

//# sourceMappingURL=config.js.map
