// Generated by CoffeeScript 1.9.3
(function() {
  var async, child_process, crypto, data_root, fs, http, io, judge_client_http, log, path, resource_dir, ss, test_script_path;

  io = require('socket.io-client');

  crypto = require('crypto');

  async = require('async');

  log = require('./log');

  child_process = require('child_process');

  ss = require('socket.io-stream');

  path = require('path');

  fs = require('fs');

  http = require('http');

  resource_dir = "/resource";

  test_script_path = path.join(__dirname, "/judge_script.py");

  data_root = '/usr/share/oj4th';

  judge_client_http = (function() {
    var self;

    self = void 0;

    function judge_client_http(data) {
      var ele, i, len, ref;
      this.name = data.name;
      this.id = data.id;
      this.tmpfs_size = data.tmpfs_size || 500;
      this.cpu_mask = 0;
      ref = data.cup;
      for (i = 0, len = ref.length; i < len; i++) {
        ele = ref[i];
        this.cpu_mask += 1 << ele;
      }
      this.task = void 0;
      this.secret_key = data.secret_key;
      this.create_time = data.create_time;
      this.log = new log(data.log_path);
      this.config = JSON.stringify(data);
      this.status = void 0;
      this.url = data.host;
      self = this;
    }

    judge_client_http.prototype.send = function(url, form) {
      var options, postData, post_time, req;
      post_time = new Date().toISOString();
      form.judge = {
        name: self.name,
        post_time: new Date(),
        token: crypto.createHash('sha1').update(self.secret_key + '$' + post_time).digest('hex')
      };
      postData = querystring.stringify(form);
      options = {
        hostname: self.host,
        port: 80,
        path: url,
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Content-Length': postData.length
        }
      };
      req = http.request(options, function(res) {
        res.setEncoding('utf8');
        return res.on('data', function(chunk) {
          return console.log('BODY: ' + chunk);
        });
      });
      req.on('error', function(e) {
        return console.log('problem with request: ' + e.message);
      });
      req.write(postData);
      return req.end();
    };

    return judge_client_http;

  })();

}).call(this);

//# sourceMappingURL=judge_client_http.js.map
